### ISSUE TITLE
Can you give me the solution for third party plugin access with "Javascript Form Validator" ?

### ISSUE THREAD

**Issue by vimal1986** [GlobalSource/javascriptFormValidator#9]
I having trouble on accessing third party plugins like Select2.

**Comment by shankarThiyagaraajan** [comment]
Hi @vimal1986 ,
Third party plugins are mostly generating alternative DOM to handling the user actions.
"Select2" will create separate input DOM to perform searches for drop down(select) box.
So, this dynamic DOM handling is not yet implemented.

But,this issue may solved on further releases.
Thank for choosing !
